# Emoji map — keyword-to-emoji mapping for video captions

import json
import os

from gui.config import EMOJIS_FILE, console, logger

DEFAULT_EMOJI_MAP = {
    "science": {"emoji": "🧪", "anim": "fade"},
    "scientific": {"emoji": "🧪", "anim": "fade"},
    "scientist": {"emoji": "🧪", "anim": "fade"},
    "physics": {"emoji": "⚛️", "anim": "fade"},
    "chemistry": {"emoji": "🧪", "anim": "fade"},
    "biology": {"emoji": "🧬", "anim": "fade"},
    "space": {"emoji": "🌌", "anim": "float_up"},
    "planet": {"emoji": "🪐", "anim": "float_up"},
    "star": {"emoji": "⭐", "anim": "pop_in"},
    "earth": {"emoji": "🌍", "anim": "fade"},
    "moon": {"emoji": "🌙", "anim": "float_up"},
    "sun": {"emoji": "☀️", "anim": "bounce"},
    "universe": {"emoji": "🌌", "anim": "float_up"},
    "galaxy": {"emoji": "🌌", "anim": "float_up"},
    "alien": {"emoji": "👽", "anim": "float_up"},
    "ufo": {"emoji": "🛸", "anim": "float_up"},
    "fact": {"emoji": "💡", "anim": "fade"},
    "facts": {"emoji": "💡", "anim": "fade"},
    "real": {"emoji": "✅", "anim": "pop_in"},
    "fake": {"emoji": "❌", "anim": "pop_in"},
    "true": {"emoji": "💯", "anim": "pop_in"},
    "false": {"emoji": "🚫", "anim": "pop_in"},
    "nature": {"emoji": "🌿", "anim": "fade"},
    "animal": {"emoji": "🐾", "anim": "fade"},
    "water": {"emoji": "💧", "anim": "fade"},
    "fire": {"emoji": "🔥", "anim": "bounce"},
    "ice": {"emoji": "❄️", "anim": "fade"},
    "history": {"emoji": "📜", "anim": "fade"},
    "historical": {"emoji": "📜", "anim": "fade"},
    "ancient": {"emoji": "🏛️", "anim": "fade"},
    "empire": {"emoji": "👑", "anim": "pop_in"},
    "king": {"emoji": "👑", "anim": "pop_in"},
    "queen": {"emoji": "👑", "anim": "pop_in"},
    "war": {"emoji": "⚔️", "anim": "shake"},
    "battle": {"emoji": "⚔️", "anim": "shake"},
    "soldier": {"emoji": "🪖", "anim": "shake"},
    "mystery": {"emoji": "❓", "anim": "fade"},
    "mysterious": {"emoji": "❓", "anim": "fade"},
    "secret": {"emoji": "🤫", "anim": "float_up"},
    "secrets": {"emoji": "🤫", "anim": "float_up"},
    "lost": {"emoji": "😵‍💫", "anim": "fade"},
    "find": {"emoji": "🔍", "anim": "fade"},
    "found": {"emoji": "🔍", "anim": "fade"},
    "search": {"emoji": "🔎", "anim": "fade"},
    "gold": {"emoji": "🪙", "anim": "pop_in"},
    "treasure": {"emoji": "💎", "anim": "pop_in"},
    "pirate": {"emoji": "🏴‍☠️", "anim": "pop_in"},
    "scary": {"emoji": "😨", "anim": "shake"},
    "creepy": {"emoji": "😰", "anim": "float_up"},
    "ghost": {"emoji": "👻", "anim": "float_up"},
    "dark": {"emoji": "🌑", "anim": "fade"},
    "phone": {"emoji": "📱", "anim": "bounce"},
    "call": {"emoji": "📞", "anim": "bounce"},
    "text": {"emoji": "💬", "anim": "bounce"},
    "message": {"emoji": "✉️", "anim": "bounce"},
    "number": {"emoji": "🔢", "anim": "bounce"},
    "cry": {"emoji": "😭", "anim": "fade"},
    "scream": {"emoji": "😱", "anim": "shake"},
    "run": {"emoji": "🏃", "anim": "bounce"},
    "fear": {"emoji": "😨", "anim": "shake"},
    "dead": {"emoji": "💀", "anim": "shake"},
    "death": {"emoji": "💀", "anim": "shake"},
    "kill": {"emoji": "🔪", "anim": "shake"},
    "killer": {"emoji": "🔪", "anim": "shake"},
    "blood": {"emoji": "🩸", "anim": "shake"},
    "night": {"emoji": "🌃", "anim": "float_up"},
    "shadow": {"emoji": "👤", "anim": "fade"},
    "monster": {"emoji": "👹", "anim": "shake"},
    "demon": {"emoji": "😈", "anim": "shake"},
    "money": {"emoji": "💵", "anim": "pop_in"},
    "rich": {"emoji": "🤑", "anim": "pop_in"},
    "poor": {"emoji": "💸", "anim": "pop_in"},
    "buy": {"emoji": "🛒", "anim": "pop_in"},
    "sell": {"emoji": "🏷️", "anim": "pop_in"},
    "dollar": {"emoji": "💵", "anim": "pop_in"},
    "dollars": {"emoji": "💵", "anim": "pop_in"},
    "cash": {"emoji": "💰", "anim": "pop_in"},
    "wealth": {"emoji": "💎", "anim": "pop_in"},
    "business": {"emoji": "💼", "anim": "pop_in"},
    "job": {"emoji": "💼", "anim": "pop_in"},
    "boss": {"emoji": "👔", "anim": "pop_in"},
    "office": {"emoji": "🏢", "anim": "pop_in"},
    "motivation": {"emoji": "🔥", "anim": "bounce"},
    "success": {"emoji": "🏆", "anim": "pop_in"},
    "lazy": {"emoji": "🛌", "anim": "fade"},
    "procrastinate": {"emoji": "⏳", "anim": "bounce"},
    "procrastination": {"emoji": "⏳", "anim": "bounce"},
    "work": {"emoji": "⚙️", "anim": "bounce"},
    "life": {"emoji": "🌱", "anim": "bounce"},
    "hack": {"emoji": "💡", "anim": "fade"},
    "hacks": {"emoji": "💡", "anim": "fade"},
    "morning": {"emoji": "🌅", "anim": "bounce"},
    "routine": {"emoji": "📅", "anim": "bounce"},
    "habit": {"emoji": "🔁", "anim": "bounce"},
    "habits": {"emoji": "🔁", "anim": "bounce"},
    "clock": {"emoji": "⏰", "anim": "bounce"},
    "time": {"emoji": "⏱️", "anim": "bounce"},
    "hour": {"emoji": "⏳", "anim": "bounce"},
    "day": {"emoji": "☀️", "anim": "bounce"},
    "school": {"emoji": "🏫", "anim": "fade"},
    "student": {"emoji": "🎓", "anim": "fade"},
    "learn": {"emoji": "📚", "anim": "fade"},
    "study": {"emoji": "📖", "anim": "fade"},
    "brain": {"emoji": "🧠", "anim": "fade"},
    "mind": {"emoji": "🧠", "anim": "fade"},
    "focus": {"emoji": "🎯", "anim": "bounce"},
    "goal": {"emoji": "🥅", "anim": "pop_in"},
    "win": {"emoji": "🥇", "anim": "pop_in"},
    "lose": {"emoji": "❌", "anim": "pop_in"},
    "computer": {"emoji": "💻", "anim": "bounce"},
    "internet": {"emoji": "🌐", "anim": "bounce"},
    "code": {"emoji": "💻", "anim": "bounce"},
    "ai": {"emoji": "🤖", "anim": "bounce"},
    "robot": {"emoji": "🤖", "anim": "bounce"},
    "game": {"emoji": "🎮", "anim": "bounce"},
    "gaming": {"emoji": "🎮", "anim": "bounce"},
    "play": {"emoji": "▶️", "anim": "bounce"},
    "music": {"emoji": "🎵", "anim": "bounce"},
    "song": {"emoji": "🎶", "anim": "bounce"},
    "video": {"emoji": "📹", "anim": "bounce"},
    "photo": {"emoji": "📷", "anim": "bounce"},
    "love": {"emoji": "❤️", "anim": "pop_in"},
    "friend": {"emoji": "🤝", "anim": "fade"},
    "people": {"emoji": "👥", "anim": "fade"},
    "man": {"emoji": "👨", "anim": "fade"},
    "woman": {"emoji": "👩", "anim": "fade"},
    "food": {"emoji": "🍔", "anim": "bounce"},
    "drink": {"emoji": "🥤", "anim": "bounce"},
    "coffee": {"emoji": "☕", "anim": "bounce"},
    "car": {"emoji": "🚗", "anim": "fade"},
    "plane": {"emoji": "✈️", "anim": "fade"},
    "house": {"emoji": "🏠", "anim": "fade"},
    "home": {"emoji": "🏠", "anim": "fade"},
    "city": {"emoji": "🏙️", "anim": "fade"},
    "world": {"emoji": "🌐", "anim": "fade"},
    "doctor": {"emoji": "👨‍⚕️", "anim": "shake"},
    "nurse": {"emoji": "👩‍⚕️", "anim": "shake"},
    "hospital": {"emoji": "🏥", "anim": "shake"},
    "medicine": {"emoji": "💊", "anim": "shake"},
    "pill": {"emoji": "💊", "anim": "shake"},
    "sick": {"emoji": "🤒", "anim": "shake"},
    "ill": {"emoji": "🤒", "anim": "shake"},
    "disease": {"emoji": "🦠", "anim": "shake"},
    "virus": {"emoji": "🦠", "anim": "shake"},
    "healthy": {"emoji": "💪", "anim": "shake"},
    "health": {"emoji": "❤️‍🩹", "anim": "shake"},
    "exercise": {"emoji": "🏋️", "anim": "bounce"},
    "gym": {"emoji": "🏋️", "anim": "bounce"},
    "workout": {"emoji": "🏋️", "anim": "bounce"},
    "injury": {"emoji": "🤕", "anim": "shake"},
    "pain": {"emoji": "😖", "anim": "shake"},
    "surgery": {"emoji": "🩺", "anim": "shake"},
    "tooth": {"emoji": "🦷", "anim": "shake"},
    "athlete": {"emoji": "🏃", "anim": "bounce"},
    "champion": {"emoji": "🏆", "anim": "pop_in"},
    "competition": {"emoji": "🤼", "anim": "shake"},
    "compete": {"emoji": "🤼", "anim": "shake"},
    "race": {"emoji": "🏁", "anim": "bounce"},
    "fight": {"emoji": "🤼‍♂️", "anim": "shake"},
    "strong": {"emoji": "💪", "anim": "bounce"},
    "football": {"emoji": "🏈", "anim": "bounce"},
    "basketball": {"emoji": "🏀", "anim": "bounce"},
    "soccer": {"emoji": "⚽", "anim": "bounce"},
    "tennis": {"emoji": "🎾", "anim": "bounce"},
    "baseball": {"emoji": "⚾", "anim": "bounce"},
    "boxing": {"emoji": "🥊", "anim": "shake"},
    "medal": {"emoji": "🥇", "anim": "pop_in"},
    "coach": {"emoji": "🧢", "anim": "bounce"},
    "trainer": {"emoji": "🧢", "anim": "bounce"},
    "happy": {"emoji": "😊", "anim": "bounce"},
    "sad": {"emoji": "😢", "anim": "fade"},
    "angry": {"emoji": "😡", "anim": "shake"},
    "anger": {"emoji": "😡", "anim": "shake"},
    "mad": {"emoji": "😡", "anim": "shake"},
    "surprised": {"emoji": "😲", "anim": "pop_in"},
    "shocked": {"emoji": "😱", "anim": "shake"},
    "laugh": {"emoji": "😂", "anim": "bounce"},
    "funny": {"emoji": "😂", "anim": "bounce"},
    "joke": {"emoji": "🤣", "anim": "bounce"},
    "crazy": {"emoji": "🤪", "anim": "bounce"},
    "confused": {"emoji": "😕", "anim": "fade"},
    "tired": {"emoji": "😩", "anim": "fade"},
    "exhausted": {"emoji": "😫", "anim": "fade"},
    "stressed": {"emoji": "😰", "anim": "shake"},
    "calm": {"emoji": "🧘", "anim": "fade"},
    "relax": {"emoji": "🧘", "anim": "fade"},
    "nervous": {"emoji": "😬", "anim": "shake"},
    "awkward": {"emoji": "😬", "anim": "shake"},
    "proud": {"emoji": "😌", "anim": "fade"},
    "embarrassed": {"emoji": "😳", "anim": "fade"},
    "shy": {"emoji": "🤭", "anim": "fade"},
    "bored": {"emoji": "🥱", "anim": "fade"},
    "lonely": {"emoji": "🥺", "anim": "fade"},
    "police": {"emoji": "👮", "anim": "shake"},
    "cop": {"emoji": "👮", "anim": "shake"},
    "lawyer": {"emoji": "⚖️", "anim": "shake"},
    "court": {"emoji": "⚖️", "anim": "shake"},
    "judge": {"emoji": "⚖️", "anim": "shake"},
    "prison": {"emoji": "⛓️", "anim": "shake"},
    "jail": {"emoji": "⛓️", "anim": "shake"},
    "thief": {"emoji": "🥷", "anim": "shake"},
    "steal": {"emoji": "🥷", "anim": "shake"},
    "stolen": {"emoji": "🥷", "anim": "shake"},
    "crime": {"emoji": "🔫", "anim": "shake"},
    "criminal": {"emoji": "⛓️", "anim": "shake"},
    "trial": {"emoji": "⚖️", "anim": "shake"},
    "arrest": {"emoji": "🚔", "anim": "shake"},
    "witness": {"emoji": "👀", "anim": "fade"},
    "lie": {"emoji": "🤥", "anim": "fade"},
    "liar": {"emoji": "🤥", "anim": "fade"},
    "innocent": {"emoji": "😇", "anim": "fade"},
    "guilty": {"emoji": "😈", "anim": "shake"},
    "family": {"emoji": "👨‍👩‍👧‍👦", "anim": "pop_in"},
    "baby": {"emoji": "👶", "anim": "pop_in"},
    "child": {"emoji": "🧒", "anim": "pop_in"},
    "parent": {"emoji": "👨‍👩‍👧", "anim": "pop_in"},
    "mother": {"emoji": "👩‍👧", "anim": "pop_in"},
    "father": {"emoji": "👨‍👧", "anim": "pop_in"},
    "mom": {"emoji": "👩‍👧", "anim": "pop_in"},
    "dad": {"emoji": "👨‍👧", "anim": "pop_in"},
    "wedding": {"emoji": "💍", "anim": "pop_in"},
    "married": {"emoji": "💍", "anim": "pop_in"},
    "couple": {"emoji": "💑", "anim": "pop_in"},
    "kiss": {"emoji": "💋", "anim": "pop_in"},
    "hug": {"emoji": "🤗", "anim": "pop_in"},
    "pet": {"emoji": "🐶", "anim": "bounce"},
    "dog": {"emoji": "🐶", "anim": "bounce"},
    "cat": {"emoji": "🐱", "anim": "bounce"},
    "broken": {"emoji": "💔", "anim": "shake"},
    "cheat": {"emoji": "🃏", "anim": "shake"},
    "alone": {"emoji": "🧍", "anim": "fade"},
    "storm": {"emoji": "🌩️", "anim": "shake"},
    "thunder": {"emoji": "⛈️", "anim": "shake"},
    "lightning": {"emoji": "⚡", "anim": "shake"},
    "rain": {"emoji": "🌧️", "anim": "fade"},
    "snowy": {"emoji": "🌨️", "anim": "float_up"},
    "tornado": {"emoji": "🌪️", "anim": "shake"},
    "wind": {"emoji": "💨", "anim": "float_up"},
    "rainbow": {"emoji": "🌈", "anim": "fade"},
    "flood": {"emoji": "🌊", "anim": "shake"},
    "disaster": {"emoji": "☄️", "anim": "shake"},
    "cloud": {"emoji": "☁️", "anim": "float_up"},
    "fog": {"emoji": "🌫️", "anim": "fade"},
    "volcano": {"emoji": "🌋", "anim": "shake"},
    "luck": {"emoji": "🍀", "anim": "pop_in"},
    "lucky": {"emoji": "🍀", "anim": "pop_in"},
    "magic": {"emoji": "✨", "anim": "pop_in"},
    "magical": {"emoji": "✨", "anim": "pop_in"},
    "dream": {"emoji": "💭", "anim": "float_up"},
    "nightmare": {"emoji": "👹", "anim": "shake"},
    "fate": {"emoji": "🔮", "anim": "fade"},
    "destiny": {"emoji": "🔮", "anim": "fade"},
    "miracle": {"emoji": "🙏", "anim": "fade"},
    "legendary": {"emoji": "🏆", "anim": "pop_in"},
    "myth": {"emoji": "🐉", "anim": "fade"},
    "fantasy": {"emoji": "🦄", "anim": "float_up"},
    "dragon": {"emoji": "🐉", "anim": "shake"},
    "unicorn": {"emoji": "🦄", "anim": "pop_in"},
    "castle": {"emoji": "🏰", "anim": "fade"},
    "hero": {"emoji": "🦸", "anim": "pop_in"},
    "villain": {"emoji": "🦹", "anim": "shake"},
    "brave": {"emoji": "🦁", "anim": "bounce"},
    "art": {"emoji": "🎨", "anim": "fade"},
    "paint": {"emoji": "🖌️", "anim": "fade"},
    "draw": {"emoji": "✍️", "anim": "fade"},
    "design": {"emoji": "🎨", "anim": "fade"},
    "creative": {"emoji": "💡", "anim": "bounce"},
    "imagine": {"emoji": "💭", "anim": "fade"},
    "write": {"emoji": "✍️", "anim": "fade"},
    "story": {"emoji": "📖", "anim": "fade"},
    "author": {"emoji": "✍️", "anim": "fade"},
    "poem": {"emoji": "📝", "anim": "fade"},
    "poetry": {"emoji": "📝", "anim": "fade"},
    "theater": {"emoji": "🎭", "anim": "fade"},
    "stage": {"emoji": "🎭", "anim": "fade"},
    "drama": {"emoji": "🎭", "anim": "shake"},
    "pizza": {"emoji": "🍕", "anim": "bounce"},
    "sushi": {"emoji": "🍣", "anim": "bounce"},
    "cake": {"emoji": "🎂", "anim": "pop_in"},
    "wine": {"emoji": "🍷", "anim": "bounce"},
    "beer": {"emoji": "🍺", "anim": "bounce"},
    "fruit": {"emoji": "🍎", "anim": "bounce"},
    "sweet": {"emoji": "🍬", "anim": "bounce"},
    "spicy": {"emoji": "🌶️", "anim": "shake"},
    "cook": {"emoji": "👨‍🍳", "anim": "bounce"},
    "chef": {"emoji": "👨‍🍳", "anim": "bounce"},
    "restaurant": {"emoji": "🍽️", "anim": "bounce"},
    "hungry": {"emoji": "🤤", "anim": "fade"},
    "taste": {"emoji": "👅", "anim": "bounce"},
    "delicious": {"emoji": "😋", "anim": "bounce"},
    "adventure": {"emoji": "🧭", "anim": "bounce"},
    "explore": {"emoji": "🔍", "anim": "fade"},
    "discover": {"emoji": "🔍", "anim": "fade"},
    "beach": {"emoji": "🏖️", "anim": "fade"},
    "mountain": {"emoji": "🏔️", "anim": "float_up"},
    "island": {"emoji": "🏝️", "anim": "fade"},
    "trip": {"emoji": "🧳", "anim": "fade"},
    "vacation": {"emoji": "🌴", "anim": "fade"},
    "camp": {"emoji": "🏕️", "anim": "fade"},
    "hike": {"emoji": "🥾", "anim": "bounce"},
    "hiking": {"emoji": "🥾", "anim": "bounce"},
    "ocean": {"emoji": "🌊", "anim": "bounce"},
    "forest": {"emoji": "🌲", "anim": "fade"},
    "river": {"emoji": "🏞️", "anim": "fade"},
    "desert": {"emoji": "🏜️", "anim": "shake"},
    "passport": {"emoji": "🛂", "anim": "fade"},
    "compass": {"emoji": "🧭", "anim": "fade"},
    "travel": {"emoji": "✈️", "anim": "fade"},
    "traveler": {"emoji": "🧳", "anim": "fade"},
    "dance": {"emoji": "💃", "anim": "bounce"},
    "dancer": {"emoji": "💃", "anim": "bounce"},
    "party": {"emoji": "🎉", "anim": "pop_in"},
    "celebrate": {"emoji": "🥳", "anim": "pop_in"},
    "celebration": {"emoji": "🎊", "anim": "pop_in"},
    "fashion": {"emoji": "👗", "anim": "fade"},
    "beauty": {"emoji": "💄", "anim": "fade"},
    "pray": {"emoji": "🙏", "anim": "fade"},
    "prayer": {"emoji": "🙏", "anim": "fade"},
    "bless": {"emoji": "✨", "anim": "fade"},
    "blessed": {"emoji": "✨", "anim": "fade"},
    "curse": {"emoji": "🤬", "anim": "shake"},
    "cursed": {"emoji": "😈", "anim": "shake"},
    "haunted": {"emoji": "🏚️", "anim": "shake"},
    "future": {"emoji": "🔮", "anim": "float_up"},
    "past": {"emoji": "⌛", "anim": "fade"},
    "energy": {"emoji": "⚡", "anim": "shake"},
    "energetic": {"emoji": "⚡", "anim": "shake"},
    "soul": {"emoji": "🕊️", "anim": "float_up"},
    "spirit": {"emoji": "✨", "anim": "float_up"},
    "spiritual": {"emoji": "🕯️", "anim": "fade"},
    "devil": {"emoji": "😈", "anim": "shake"},
    "angel": {"emoji": "😇", "anim": "fade"},
    "warrior": {"emoji": "⚔️", "anim": "shake"},
    "hunt": {"emoji": "🏹", "anim": "shake"},
    "hunter": {"emoji": "🏹", "anim": "shake"},
    "smile": {"emoji": "😊", "anim": "bounce"},
    "grin": {"emoji": "😁", "anim": "bounce"},
    "afraid": {"emoji": "😨", "anim": "shake"},
    "terrified": {"emoji": "😱", "anim": "shake"},
    "protect": {"emoji": "🛡️", "anim": "fade"},
    "protection": {"emoji": "🛡️", "anim": "fade"},
    "build": {"emoji": "🔧", "anim": "bounce"},
    "builder": {"emoji": "👷", "anim": "bounce"},
    "grow": {"emoji": "🌱", "anim": "float_up"},
    "growth": {"emoji": "📈", "anim": "float_up"},
    "fly": {"emoji": "🕊️", "anim": "float_up"},
    "swim": {"emoji": "🏊", "anim": "bounce"},
    "read": {"emoji": "📖", "anim": "fade"},
    "sing": {"emoji": "🎤", "anim": "bounce"},
    "singer": {"emoji": "🎤", "anim": "bounce"},
    "style": {"emoji": "💅", "anim": "fade"},
    "tears": {"emoji": "😭", "anim": "fade"},
}


def _normalize_emoji_map(raw_map: dict) -> dict:
    """Normalize emoji_map entries so each value is a dict with 'emoji' and 'anim' keys."""
    normalized = {}
    for key, value in raw_map.items():
        if isinstance(value, str):
            normalized[key] = {"emoji": value, "anim": "none"}
        elif isinstance(value, dict):
            normalized[key] = {
                "emoji": value.get("emoji", "❓"),
                "anim": value.get("anim", "none"),
            }
        else:
            normalized[key] = {"emoji": str(value), "anim": "none"}
    return normalized


def load_emoji_map() -> dict:
    if not os.path.exists(EMOJIS_FILE):
        try:
            with open(EMOJIS_FILE, "w", encoding="utf-8") as f:
                json.dump(DEFAULT_EMOJI_MAP, f, indent=4, ensure_ascii=False)
            return _normalize_emoji_map(DEFAULT_EMOJI_MAP)
        except Exception as e:
            logger.warning(
                f"Failed to create default emoji map file at {EMOJIS_FILE}: {e}", exc_info=True
            )
            return _normalize_emoji_map(DEFAULT_EMOJI_MAP)
    try:
        with open(EMOJIS_FILE, encoding="utf-8") as f:
            raw = json.load(f)
            return _normalize_emoji_map(raw)
    except Exception as e:
        logger.warning(f"Failed to load emoji map from {EMOJIS_FILE}: {e}", exc_info=True)
        return _normalize_emoji_map(DEFAULT_EMOJI_MAP)


def save_emoji_map(emoji_map: dict) -> bool:
    try:
        with open(EMOJIS_FILE, "w", encoding="utf-8") as f:
            json.dump(emoji_map, f, indent=4, ensure_ascii=False)
        return True
    except Exception as e:
        logger.warning(f"Failed to save emoji map to {EMOJIS_FILE}: {e}", exc_info=True)
        return False
